### ISSUE TITLE
Better 404 page

### ISSUE THREAD

**Issue by colintate** [emmapersky/one-click-orgs#100] opened 2010-03-28 16:50 UTC
http://rails3.oneclickorgs.com/members/40000 - should this be more cosmetically handled?  (still with messaging, but with easier nav ability to get back in?

**Comment by chrismear** [comment] 2010-03-29 14:14
404 template needs to be added:

```
ActionView::MissingTemplate (Missing template //home/oneclickorgs/var/www/rails3.oneclickorgs.com/public/404.html with {:formats=>[:html]} in view path /home/oneclickorgs/var/www/rails3.oneclickorgs.com/app/views:/home/oneclickorgs/var/www/rails3.oneclickorgs.com/vendor/plugins/haml/app/views):
  app/controllers/application_controller.rb:95:in `render_404'
```

**Comment by chrismear** [comment] 2010-04-02 00:12
The 404.html template is actually already there, but that ActionView::MissingTemplate is being caused by a Rails bug that's fixed in 3.0.0.beta2: http://github.com/rails/rails/commit/ae933a093db93c22b9facd3411afd9ef69719193

The template still needs prettying up, though.

**Comment by chrismear** [comment] 2010-11-05 22:59
This ticket now at:

https://github.com/oneclickorgs/one-click-orgs/issues/100

**Closed as completed by chrismear** 2010-11-05 22:59 UTC
Labels: ux, v1.0
